baseURL = "https://getbtcz.com"
languageCode = "en-us"
title = "BitcoinZ - Community-Driven Cryptocurrency"
theme = "PaperMod"

# Ignore raw HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']

# Enable raw HTML in markdown
[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "BitcoinZ - A decentralized cryptocurrency focused on privacy security and true community governance"
  keywords = "BitcoinZ cryptocurrency decentralization privacy blockchain"
  author = "BitcoinZ Community"

  # Social Media Links
  github = "https://github.com/simbav911/dart-naujas-btcz.rock"
  twitter = "https://twitter.com/bitcoinz_team"
  telegram = "https://t.me/bitcoinzcommunity"
  discord = "https://discord.gg/bitcoinz"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "why-bitcoinz"
    name = "Why BTCZ"
    url = "/why-bitcoinz/"
    weight = 2
  [[menu.main]]
    identifier = "ecosystem"
    name = "Eco"
    url = "/ecosystem/"
    weight = 3
  [[menu.main]]
    identifier = "wallets"
    name = "Wallets"
    url = "/wallets/"
    weight = 4
  [[menu.main]]
    identifier = "buy"
    name = "Buy"
    url = "/buy/"
    weight = 5
  [[menu.main]]
    identifier = "learn-crypto"
    name = "Learn"
    url = "/learn/"
    weight = 6
  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 7
  [[menu.main]]
    identifier = "roadmap"
    name = "Map"
    url = "/roadmap/"
    weight = 8
  [[menu.main]]
    identifier = "halving"
    name = "Halving"
    url = "/halving/"
    weight = 9
  [[menu.main]]
    identifier = "vaultz"
    name = "VaultZ"
    url = "/vaultz/"
    weight = 10
  [[menu.main]]
    identifier = "vertex"
    name = "Vertex"
    url = "/vertex/"
    weight = 11
  [[menu.main]]
    identifier = "earn"
    name = "Earn"
    url = "/earn/"
    weight = 12

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
